# SPDX-FileCopyrightText: 2025 DESY and the Constellation authors
# SPDX-License-Identifier: CC0-1.0

name: Constellation GitHub CI Pipeline

on:
  push:
    branches: [ '**' ]
  pull_request:

jobs:
  lint-mypy:
    name: Lint (mypy)
    runs-on: ubuntu-latest
    container:
      image: python:3.11
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python virtualenv
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip setuptools
          pip install --no-build-isolation -e .[dev]

      - name: Run mypy
        run: |
          source venv/bin/activate
          mypy src/

  format-black:
    name: Format Check (black)
    runs-on: ubuntu-latest
    container:
      image: python:3.11
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python virtualenv
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip setuptools
          pip install --no-build-isolation -e .[dev]

      - name: Check black formatting
        run: |
          source venv/bin/activate
          black --check src/

  format-isort:
    name: Format (isort)
    runs-on: ubuntu-latest
    container:
      image: python:3.11
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python virtualenv
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip setuptools
          pip install --no-build-isolation -e .[dev]

      - name: Check isort formatting
        run: |
          source venv/bin/activate
          isort --check .

  format-flake8:
    name: Format (flake8)
    runs-on: ubuntu-latest
    container:
      image: python:3.11
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python virtualenv
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip setuptools
          pip install --no-build-isolation -e .[dev]

      - name: Run flake8
        run: |
          source venv/bin/activate
          flake8 src/

  format-reuse:
    name: Format (reuse)
    runs-on: ubuntu-latest
    container:
      image: fsfe/reuse:latest
    steps:
      - uses: actions/checkout@v4

      - name: Run reuse lint
        run: reuse lint

  format-codespell:
    name: Format (codespell)
    runs-on: ubuntu-latest
    container:
      image: python:3.11
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python virtualenv
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip setuptools
          pip install --no-build-isolation -e .[dev]

      - name: Run codespell
        run: |
          source venv/bin/activate
          codespell
